services:
  simulation-app:
    image: ghcr.io/glDemonti/rc-model-building-simulation:latest
    container_name: simulation-app
    ports:
      - "8050:8050"
    volumes:
      - ./projects:/app/projects
      - ./data:/app/data
    environment:
      - VM2_DATA_DIR=/app/data
