services:
  simulation-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vm2-rc-modell-ui:local
    container_name: simulation-app
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    environment:
      - VM2_DATA_DIR=/app/data
