services:
  simulation-app:
    image: ghcr.io/gldemonti/rc-model-building-simulation:1.0.1
    pull_policy: if_not_present
    container_name: simulation-app
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    environment:
      - VM2_DATA_DIR=/app/data